import { useEffect } from 'react';
import { DEFAULT_OG_IMAGE, SITE_NAME, SITE_ORIGIN } from './site';

type SeoInput = { title: string; description: string; path?: string; image?: string; noindex?: boolean; jsonLd?: Record<string, unknown> };
function meta(name:string, content:string, property=false){const selector=property?`meta[property="${name}"]`:`meta[name="${name}"]`;let el=document.head.querySelector<HTMLMetaElement>(selector);if(!el){el=document.createElement('meta');el.setAttribute(property?'property':'name',name);document.head.appendChild(el);}el.content=content;}
function linkCanonical(url:string){let el=document.head.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(!el){el=document.createElement('link');el.rel='canonical';document.head.appendChild(el);}el.href=url;}
function jsonLd(value:Record<string,unknown>|undefined){let el=document.getElementById('page-jsonld') as HTMLScriptElement|null;if(!value){el?.remove();return;}if(!el){el=document.createElement('script');el.type='application/ld+json';el.id='page-jsonld';document.head.appendChild(el);}el.textContent=JSON.stringify(value);}
export function applySeo(input:SeoInput){const canonical=`${SITE_ORIGIN}${input.path||location.pathname}`;const image=input.image?(input.image.startsWith('http')?input.image:`${SITE_ORIGIN}${input.image.startsWith('/')?'':'/'}${input.image}`):DEFAULT_OG_IMAGE;document.title=input.title;meta('description',input.description);meta('robots',input.noindex?'noindex,nofollow':'index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1');meta('og:title',input.title,true);meta('og:description',input.description,true);meta('og:type','website',true);meta('og:url',canonical,true);meta('og:site_name',SITE_NAME,true);meta('og:image',image,true);meta('twitter:card','summary_large_image');meta('twitter:title',input.title);meta('twitter:description',input.description);meta('twitter:image',image);linkCanonical(canonical);jsonLd(input.jsonLd);}
export function usePageSeo(input:SeoInput|null){useEffect(()=>{if(input)applySeo(input);},[input?.title,input?.description,input?.path,input?.image,input?.noindex,JSON.stringify(input?.jsonLd||null)]);}
