import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
function normalizeOrigin(value:string){return value.trim().replace(/\/+$/,'');}
const configuredOrigin=normalizeOrigin(Deno.env.get('SALLA_BROWSER_ORIGIN')||'https://browser.salla-shop.com');
function corsHeaders(req:Request){const origin=normalizeOrigin(req.headers.get('Origin')||'');return{'Access-Control-Allow-Origin':origin===configuredOrigin?origin:configuredOrigin,'Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Cache-Control':'no-store','Vary':'Origin'};}
function json(req:Request,body:Record<string,unknown>,status=200){return new Response(JSON.stringify(body),{status,headers:{...corsHeaders(req),'Content-Type':'application/json'}});}
function validCheckoutUrl(value:unknown){if(typeof value!=='string'||!value)return false;try{const u=new URL(value);return u.protocol==='https:'&&u.hostname==='mall.salla-shop.com'&&u.pathname.startsWith('/api-checkout/');}catch{return false;}}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders(req)});if(req.method!=='POST')return json(req,{success:false,error:'method_not_allowed'},405);try{
 const supabaseUrl=Deno.env.get('SUPABASE_URL')||'';const anonKey=Deno.env.get('SUPABASE_ANON_KEY')||'';const serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';const apiKey=Deno.env.get('SALLA_SHOP_API_KEY')||'';
 if(!supabaseUrl||!anonKey||!serviceKey||!apiKey)return json(req,{success:false,error:'payment_setup_incomplete'},503);
 const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!token)return json(req,{success:false,error:'unauthorized'},401);
 const authClient=createClient(supabaseUrl,anonKey,{auth:{persistSession:false,autoRefreshToken:false}});const{data:authData,error:authError}=await authClient.auth.getUser(token);const user=authData.user;if(authError||!user)return json(req,{success:false,error:'unauthorized'},401);
 const body=await req.json().catch(()=>({}));const promotionId=typeof body?.promotion_id==='string'?body.promotion_id:'';if(!promotionId)return json(req,{success:false,error:'missing_promotion'},400);
 const admin=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});const{data:promotion,error}=await admin.from('app_promotions').select('id,user_id,app_id,kind,duration_days,amount,currency,status,payment_transaction_id,payment_checkout_url,app:apps(name)').eq('id',promotionId).eq('user_id',user.id).maybeSingle();
 if(error||!promotion)return json(req,{success:false,error:'promotion_not_found'},404);if(promotion.status==='active')return json(req,{success:false,error:'payment_already_completed'},409);if(promotion.status!=='awaiting_payment')return json(req,{success:false,error:'payment_unavailable'},409);
 if(promotion.payment_checkout_url&&promotion.payment_transaction_id&&validCheckoutUrl(promotion.payment_checkout_url))return json(req,{success:true,transaction_id:promotion.payment_transaction_id,checkout_url:promotion.payment_checkout_url,reused:true});
 const amount=Number(promotion.amount||0);if(!(amount>0))return json(req,{success:false,error:'invalid_amount'},400);const appName=Array.isArray(promotion.app)?promotion.app[0]?.name:promotion.app?.name;const label=promotion.kind==='home_ad'?'Salla Browser home ad':'Salla Browser app boost';
 const providerResponse=await fetch('https://iagohfijczwnuihedsml.supabase.co/functions/v1/extapi-create-checkout',{method:'POST',headers:{'X-API-Key':apiKey,'Content-Type':'application/json','Origin':configuredOrigin},body:JSON.stringify({amount,currency:'pi',description:`${label} ${appName||promotion.app_id}`,success_url:`${configuredOrigin}/promote?payment=success&promotion=${encodeURIComponent(promotion.id)}&app=${encodeURIComponent(promotion.app_id)}`,cancel_url:`${configuredOrigin}/promote?payment=cancelled&promotion=${encodeURIComponent(promotion.id)}&app=${encodeURIComponent(promotion.app_id)}`})});
 const providerBody=await providerResponse.json().catch(()=>({}));if(!providerResponse.ok||!providerBody?.success||!providerBody?.transaction_id||!validCheckoutUrl(providerBody?.checkout_url))return json(req,{success:false,error:'provider_rejected'},502);
 const{error:saveError}=await admin.from('app_promotions').update({payment_transaction_id:String(providerBody.transaction_id),payment_checkout_url:String(providerBody.checkout_url),payment_started_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',promotion.id).eq('user_id',user.id);if(saveError)return json(req,{success:false,error:'checkout_save_failed'},500);
 return json(req,{success:true,transaction_id:providerBody.transaction_id,checkout_url:providerBody.checkout_url,reused:false});
}catch{return json(req,{success:false,error:'service_unavailable'},500);}});
