import { AlertTriangle, ArrowLeft, ArrowRight, ExternalLink, Flag, Home, LoaderCircle, RefreshCw, ShieldCheck, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useLanguage } from '../contexts/LanguageContext';
import { safeHostname } from '../lib/url';
import type { EmbedMode } from '../types';
import { ReportAppDialog } from './ReportAppDialog';

export function BrowserFrame({ url, title, appId, appName, mode='iframe' }: { url:string; title?:string; appId?:string; appName?:string; mode?:EmbedMode }) {
  const navigate=useNavigate(); const{language}=useLanguage(); const[loading,setLoading]=useState(true); const[slow,setSlow]=useState(false); const[frameKey,setFrameKey]=useState(0); const[reportOpen,setReportOpen]=useState(false);
  useEffect(()=>{setLoading(true);setSlow(false);const timer=window.setTimeout(()=>setSlow(true),9000);return()=>window.clearTimeout(timer)},[frameKey,url]);
  useEffect(()=>{const refresh=()=>{setSlow(false);setLoading(true);setFrameKey(k=>k+1)};window.addEventListener('salla-refresh-frame',refresh);return()=>window.removeEventListener('salla-refresh-frame',refresh)},[]);
  const retry=()=>{setSlow(false);setLoading(true);setFrameKey(k=>k+1)}; const ar=language==='ar';
  return <><div className="browser-frame-shell browser-frame-immersive"><div className="browser-toolbar browser-toolbar-v16"><button className="browser-tool" onClick={()=>navigate(-1)} aria-label={ar?'رجوع':'Back'}><ArrowLeft/></button><button className="browser-tool" onClick={()=>navigate(1)} aria-label={ar?'تقدم':'Forward'}><ArrowRight/></button><button className="browser-tool" onClick={retry} aria-label={ar?'تحديث':'Refresh'}><RefreshCw/></button><div className="browser-address min-w-0 flex-1"><ShieldCheck className="shrink-0 text-emerald-400"/><div className="min-w-0"><div className="truncate text-[11px] font-black">{title||safeHostname(url)}</div><div className="muted-text truncate text-[9px] font-bold" dir="ltr">{safeHostname(url)}</div></div></div>{appId&&<button className="browser-tool" onClick={()=>setReportOpen(true)} aria-label={ar?'إبلاغ':'Report'}><Flag/></button>}<a className="browser-tool" href={url} target="_blank" rel="noreferrer" aria-label={ar?'فتح خارجيا':'Open externally'}><ExternalLink/></a><button className="browser-tool" onClick={()=>navigate('/')} aria-label={ar?'الرئيسية':'Home'}><Home/></button><button className="browser-tool" onClick={()=>navigate('/')} aria-label={ar?'إغلاق':'Close'}><X/></button></div>{mode==='limited'&&<div className="browser-limited-note"><AlertTriangle/>{ar?'قد تحتاج بعض وظائف هذا التطبيق للفتح خارج Salla Browser':'Some features may require opening this app externally'}</div>}<div className="browser-viewport relative flex-1 overflow-hidden bg-white">{loading&&<div className="browser-loading absolute inset-0 z-10 flex flex-col items-center justify-center gap-3 px-5 text-center"><LoaderCircle className="browser-loader-icon h-8 w-8 text-cyan-400"/><span className="text-xs font-black">{ar?'جاري فتح التطبيق':'Opening app'}</span>{slow&&<div className="browser-slow-card"><strong>{ar?'يستغرق التطبيق وقتا أطول من المعتاد':'This app is taking longer than usual'}</strong><p>{ar?'يمكنك إعادة المحاولة أو فتح التطبيق خارج المتصفح':'Retry or open the app in a separate browser window.'}</p><div><button className="secondary-button" onClick={retry}><RefreshCw/>{ar?'إعادة المحاولة':'Retry'}</button><a className="primary-button" href={url} target="_blank" rel="noreferrer"><ExternalLink/>{ar?'فتح خارجيا':'Open externally'}</a></div></div>}</div>}<iframe key={frameKey} src={url} title={title||'Salla Browser'} onLoad={()=>{setLoading(false);setSlow(false)}} className="browser-iframe w-full border-0 bg-white" sandbox="allow-forms allow-modals allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-downloads allow-top-navigation-by-user-activation allow-top-navigation-to-custom-protocols" referrerPolicy="strict-origin-when-cross-origin"/></div></div>{appId&&<ReportAppDialog open={reportOpen} onClose={()=>setReportOpen(false)} appId={appId} appName={appName||title||safeHostname(url)} source="browser-toolbar"/>}</>;
}
