import { useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import { useLanguage } from '../contexts/LanguageContext';
import { applySeo } from '../lib/usePageSeo';
import { DEFAULT_OG_IMAGE, SITE_ORIGIN } from '../lib/site';

const privatePaths=['/login','/register','/profile','/submit','/my-submissions','/admin','/browse','/favorites','/auth'];
export function SeoManager(){const location=useLocation();const {language}=useLanguage();useEffect(()=>{const ar=language==='ar';const path=location.pathname;let title=ar?'Salla Browser | متصفح تطبيقات Salla وWeb3':'Salla Browser | Salla Apps & Web3 Directory';let description=ar?'اكتشف تطبيقات منظومة Salla المعتمدة فلتر حسب الدولة ثبت تطبيقاتك المفضلة وابحث على الويب من تجربة سريعة وخفيفة':'Discover approved Salla ecosystem apps, filter by country, pin favorites, and search the web from one fast lightweight experience.';if(path==='/explore'){title=ar?'استكشف تطبيقات Salla | Salla Browser':'Explore Salla Apps | Salla Browser';description=ar?'دليل تطبيقات Salla المعتمدة مع فلترة حسب القسم والدولة':'Browse approved Salla apps with category and country filters.';}else if(path==='/favorites'){title=ar?'التطبيقات المثبتة | Salla Browser':'Pinned Apps | Salla Browser';description=ar?'تطبيقاتك المثبتة محليا على هذا الجهاز':'Apps pinned locally on this device.';}else if(path==='/submit'){title=ar?'إدراج تطبيق للمطورين | Salla Browser':'Developer App Submission | Salla Browser';description=ar?'بوابة المطورين لتقديم تطبيق جديد إلى دليل Salla Browser ومتابعة المراجعة':'Developer portal for submitting apps to the Salla Browser directory.';}else if(path==='/login'||path==='/register'){title=ar?'بوابة المطورين | Salla Browser':'Developer Portal | Salla Browser';description=ar?'تسجيل دخول وإنشاء حساب للمطورين وأصحاب التطبيقات فقط':'Developer-only sign in and account creation.';}
const noindex=privatePaths.some((p)=>path===p||path.startsWith(`${p}/`)) || (path==='/' && new URLSearchParams(location.search).has('q'));applySeo({title,description,path,image:DEFAULT_OG_IMAGE,noindex,jsonLd:path==='/'?{'@context':'https://schema.org','@graph':[{'@type':'WebSite',name:'Salla Browser',url:SITE_ORIGIN,inLanguage:['ar','en'],potentialAction:{'@type':'SearchAction',target:`${SITE_ORIGIN}/?q={search_term_string}`,'query-input':'required name=search_term_string'}},{'@type':'WebApplication',name:'Salla Browser',url:SITE_ORIGIN,applicationCategory:'BrowserApplication',operatingSystem:'Any',description,offers:{'@type':'Offer',price:'0',priceCurrency:'USD'}}]}:undefined});},[language,location.pathname,location.search]);return null;}
