import { useEffect } from 'react';
import { Route, Routes, useLocation } from 'react-router-dom';
import { AppShell } from './components/AppShell';
import { SeoManager } from './components/SeoManager';
import { AdminRoute, DeveloperRoute } from './components/ProtectedRoute';
import AuthCallback from './pages/AuthCallback'; import Admin from './pages/Admin'; import AppDetails from './pages/AppDetails'; import BrowserPage from './pages/Browser'; import Explore from './pages/Explore'; import Favorites from './pages/Favorites'; import Home from './pages/Home'; import Login from './pages/Login'; import MySubmissions from './pages/MySubmissions'; import NotFound from './pages/NotFound';
import AdminPromotions from './pages/AdminPromotions'; import ListingCheckout from './pages/ListingCheckout'; import PromotionCheckout from './pages/PromotionCheckout'; import PromoteApp from './pages/PromoteApp'; import Profile from './pages/Profile'; import Register from './pages/Register'; import SubmitApp from './pages/SubmitApp';
function ScrollToTop(){const { pathname }=useLocation();useEffect(()=>{if(pathname!=='/browse') window.scrollTo({top:0,left:0,behavior:'auto'});},[pathname]);return null;}
export default function App(){return <><SeoManager/><ScrollToTop/><Routes><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/auth/callback" element={<AuthCallback/>}/><Route path="/listing-checkout" element={<DeveloperRoute><ListingCheckout/></DeveloperRoute>}/><Route path="/promotion-checkout" element={<DeveloperRoute><PromotionCheckout/></DeveloperRoute>}/><Route element={<AppShell/>}><Route index element={<Home/>}/><Route path="explore" element={<Explore/>}/><Route path="apps/:slug" element={<AppDetails/>}/><Route path="browse" element={<BrowserPage/>}/><Route path="favorites" element={<Favorites/>}/><Route path="profile" element={<DeveloperRoute><Profile/></DeveloperRoute>}/><Route path="submit" element={<DeveloperRoute><SubmitApp/></DeveloperRoute>}/><Route path="my-submissions" element={<DeveloperRoute><MySubmissions/></DeveloperRoute>}/><Route path="promote" element={<DeveloperRoute><PromoteApp/></DeveloperRoute>}/><Route path="admin" element={<AdminRoute><Admin/></AdminRoute>}/><Route path="admin/promotions" element={<AdminRoute><AdminPromotions/></AdminRoute>}/><Route path="*" element={<NotFound/>}/></Route></Routes></>;}
